---
title: "datafest"
author: Angie Shen, Sam Yin, Haozhang Jiang, Pim Chuaylua
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(magrittr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(data.table)
```

```{r load data set, message=FALSE, warning=FALSE}
data <- fread("/datafest/ASADataFest2017_Data/data.txt")
dest <- fread("/datafest/ASADataFest2017_Data/dest.txt")
class(data) = "data.frame"
class(dest) = "data.frame"

# create sample
#set.seed(20170401)
#sample <- data %>% sample_frac(0.01)
#save(sample, file = "sample.RData")

# convert the ordinal variables to numerical levels
data <- data %>% mutate(distance_band_f = 
           as.numeric(factor(distance_band, 
                             levels = c("VC", "C", "M", "F", "VF"), 
                             ordered = TRUE))) %>% 
  mutate(hist_price_band_f = 
           as.numeric(factor(hist_price_band, 
                             levels = c("VL", "L", "M", "H", "VH"), 
                             ordered = TRUE))) %>% 
  mutate(popularity_band_f = 
           as.numeric(factor(popularity_band, 
                             levels = c("VL", "L", "M", "H", "VH"), 
                             ordered = TRUE))) %>% 
  select(-(24:26))
```

```{r merge}
data_merge <- left_join(data, dest)
```

```{r, message=FALSE, warning=FALSE}
# group sessions with identical travel plans
data_booked <- data %>% arrange(date_time) %>% 
  group_by(user_id, srch_ci, srch_co, hotel_country) %>% 
  summarize(is_booking = as.integer(any(is_booking == 1)), 
            srch_count = n(), 
            srch_count_unique = sum(cnt == 1), 
            distance = median(as.numeric(orig_destination_distance), 
                              na.rm = TRUE), 
            is_mobile = as.integer(any(is_mobile == 1)), 
            is_package = as.integer(any(is_package == 1)), 
            channel = last(channel), 
            adults_cnt = last(srch_adults_cnt), 
            children_cnt = last(srch_children_cnt), 
            rm_cnt = last(srch_rm_cnt), 
            prop_is_branded = last(prop_is_branded), 
            prop_starrating = last(prop_starrating), 
            distance_band = last(distance_band_f), 
            hist_price_band = last(hist_price_band_f), 
            popularity_band = last(popularity_band_f))
```

```{r continuation ratio model, message=FALSE, warning=FALSE}
# select the columns with predictors
booking_count <- data_booked %>% filter(is_booking == 1) %>% 
  select(srch_count:popularity_band) %>% ungroup() %>% 
  select(-(user_id:hotel_country), -srch_count_unique)

# group all search counts >5 as one category
booking_count$srch_count[booking_count$srch_count > 5] = 6

# transform the data set
d <- 6
q <- d - 1 + ncol(booking_count) - 1
n <- nrow(booking_count)
N <- sum(booking_count$srch_count) - 
  sum(booking_count$srch_count == max(booking_count$srch_count))

y <- vector(length = N)
W <- matrix(nrow = N, ncol = d - 1)
x <- matrix(nrow = N, ncol = ncol(booking_count))
s <- 0
for (i in 1:n) {
  if (booking_count$srch_count[i] == 1) {
    y[s + 1] <- 1
    W[s + 1, 1] <- 1
    W[s + 1, -1] <- rep(0, d - 2)
    x[s + 1, 1] <- i
    s <- s + 1
  } else if (booking_count$srch_count[i] == d) {
    y[(s + 1):(s + d - 1)] <- 0
    W[(s + 1):(s + d - 1), ] <- diag(d - 1)
    x[(s + 1):(s + d - 1), 1] <- rep(i, d - 1)
    s <- s + d - 1
  } else {
    r <- booking_count$srch_count[i]
    y[(s + 1):(s + r - 1)] <- 0
    y[s + r] <- 1
    W[(s + 1):(s + r), ] <- diag(d - 1)[1:r, ]
    x[(s + 1):(s + r), 1] <- rep(i, r)
    s <- s + r
  }
}
for (j in 1:N) {
  for (k in 2:ncol(booking_count)) {
    x[j, k] <- as.numeric(booking_count[x[j, 1], k])
  }
}
data_trans <- as.data.frame(cbind(W, x[, -1], y))
colnames(data_trans) <- c(paste0("srch_", 1:(d - 1)), 
                          colnames(booking_count)[-1], "booking")
rm(W, x, y, i, j, k, r, s)

# run the model in a frequentist approach
model_1 <- glm(booking ~ -1 + ., data = data_trans, 
               family = binomial(link = "probit"), 
               na.action = "na.omit")
summary(model_1)
# extract coefficients
coef_1 <- model_1$coefficients
```

```{r continuation ratio model on US users, message=FALSE, warning=FALSE}
data_booked_us <- data %>% 
  filter(user_location_country == "UNITED STATES OF AMERICA") %>% 
  arrange(date_time) %>% 
  group_by(user_id, srch_ci, srch_co, hotel_country) %>% 
  summarize(is_booking = as.integer(any(is_booking == 1)), 
            srch_count = n(), 
            srch_count_unique = sum(cnt == 1), 
            distance = median(as.numeric(orig_destination_distance), 
                              na.rm = TRUE), 
            is_mobile = as.integer(any(is_mobile == 1)), 
            is_package = as.integer(any(is_package == 1)), 
            channel = last(channel), 
            adults_cnt = last(srch_adults_cnt), 
            children_cnt = last(srch_children_cnt), 
            rm_cnt = last(srch_rm_cnt), 
            prop_is_branded = last(prop_is_branded), 
            prop_starrating = last(prop_starrating), 
            distance_band = last(distance_band_f), 
            hist_price_band = last(hist_price_band_f), 
            popularity_band = last(popularity_band_f))

booking_count_us <- data_booked_us %>% filter(is_booking == 1) %>% 
  ungroup() %>% 
  select(-(user_id:is_booking), -srch_count_unique)
booking_count_us$srch_count[booking_count_us$srch_count > 5] = 6

d <- 6
q <- d - 1 + ncol(booking_count_us) - 1
n <- nrow(booking_count_us)
N <- sum(booking_count_us$srch_count) - 
  sum(booking_count_us$srch_count == max(booking_count_us$srch_count))

y <- vector(length = N)
W <- matrix(nrow = N, ncol = d - 1)
x <- matrix(nrow = N, ncol = ncol(booking_count_us))
s <- 0
for (i in 1:n) {
  if (booking_count_us$srch_count[i] == 1) {
    y[s + 1] <- 1
    W[s + 1, 1] <- 1
    W[s + 1, -1] <- rep(0, d - 2)
    x[s + 1, 1] <- i
    s <- s + 1
  } else if (booking_count_us$srch_count[i] == d) {
    y[(s + 1):(s + d - 1)] <- 0
    W[(s + 1):(s + d - 1), ] <- diag(d - 1)
    x[(s + 1):(s + d - 1), 1] <- rep(i, d - 1)
    s <- s + d - 1
  } else {
    r <- booking_count_us$srch_count[i]
    y[(s + 1):(s + r - 1)] <- 0
    y[s + r] <- 1
    W[(s + 1):(s + r), ] <- diag(d - 1)[1:r, ]
    x[(s + 1):(s + r), 1] <- rep(i, r)
    s <- s + r
  }
}
for (j in 1:N) {
  for (k in 2:ncol(booking_count_us)) {
    x[j, k] <- as.numeric(booking_count_us[x[j, 1], k])
  }
}
data_trans_us <- as.data.frame(cbind(W, x[, -1], y))
colnames(data_trans_us) <- c(paste0("srch_", 1:(d - 1)), 
                          colnames(booking_count_us)[-1], "booking")
rm(W, x, y, i, j, k, r, s)

model_us <- glm(booking ~ -1 + ., data = data_trans_us, 
               family = binomial(link = "probit"), 
               na.action = "na.omit")
summary_us <- summary(model_us)
coef_us <- summary_us$coefficients
save(coef_us, file = "coef_us.RData")
```

```{r continuation ratio model on German users, message=FALSE, warning=FALSE}
data_booked_de <- data %>% 
  filter(user_location_country == "GERMANY") %>% 
  arrange(date_time) %>% 
  group_by(user_id, srch_ci, srch_co, hotel_country) %>% 
  summarize(is_booking = as.integer(any(is_booking == 1)), 
            srch_count = n(), 
            srch_count_unique = sum(cnt == 1), 
            distance = median(as.numeric(orig_destination_distance), 
                              na.rm = TRUE), 
            is_mobile = as.integer(any(is_mobile == 1)), 
            is_package = as.integer(any(is_package == 1)), 
            channel = last(channel), 
            adults_cnt = last(srch_adults_cnt), 
            children_cnt = last(srch_children_cnt), 
            rm_cnt = last(srch_rm_cnt), 
            prop_is_branded = last(prop_is_branded), 
            prop_starrating = last(prop_starrating), 
            distance_band = last(distance_band_f), 
            hist_price_band = last(hist_price_band_f), 
            popularity_band = last(popularity_band_f))

booking_count_de <- data_booked_de %>% filter(is_booking == 1) %>% 
  ungroup() %>% 
  select(-(user_id:is_booking), -srch_count_unique)
booking_count_de$srch_count[booking_count_de$srch_count > 5] = 6

d <- 6
q <- d - 1 + ncol(booking_count_de) - 1
n <- nrow(booking_count_de)
N <- sum(booking_count_de$srch_count) - 
  sum(booking_count_de$srch_count == max(booking_count_de$srch_count))

y <- vector(length = N)
W <- matrix(nrow = N, ncol = d - 1)
x <- matrix(nrow = N, ncol = ncol(booking_count_de))
s <- 0
for (i in 1:n) {
  if (booking_count_de$srch_count[i] == 1) {
    y[s + 1] <- 1
    W[s + 1, 1] <- 1
    W[s + 1, -1] <- rep(0, d - 2)
    x[s + 1, 1] <- i
    s <- s + 1
  } else if (booking_count_de$srch_count[i] >= d) {
    y[(s + 1):(s + d - 1)] <- 0
    W[(s + 1):(s + d - 1), ] <- diag(d - 1)
    x[(s + 1):(s + d - 1), 1] <- rep(i, d - 1)
    s <- s + d - 1
  } else {
    r <- booking_count_de$srch_count[i]
    y[(s + 1):(s + r - 1)] <- 0
    y[s + r] <- 1
    W[(s + 1):(s + r), ] <- diag(d - 1)[1:r, ]
    x[(s + 1):(s + r), 1] <- rep(i, r)
    s <- s + r
  }
}
for (j in 1:N) {
  for (k in 2:ncol(booking_count_de)) {
    x[j, k] <- as.numeric(booking_count_de[x[j, 1], k])
  }
}
data_trans_de <- as.data.frame(cbind(W, x[, -1], y))
colnames(data_trans_de) <- c(paste0("srch_", 1:(d - 1)), 
                          colnames(booking_count_de)[-1], "booking")
rm(W, x, y, i, j, k, r, s)

model_de <- glm(booking ~ -1 + ., data = data_trans_de, 
               family = binomial(link = "probit"), 
               na.action = "na.omit")
summary_de <- summary(model_de)
coef_de <- summary_de$coefficients
```

```{r search counts}
# extract date_time and destinations without NA
complete_search <- data_merge %>% 
#  filter(user_location_country == "UNITED STATES OF AMERICA") %>% 
  select(date_time, srch_destination_name) %>% 
  as.data.frame() %>% .[complete.cases(.), ]

# weekly search counts on Paris
search_count_paris <- complete_search %>% 
  filter(srch_destination_name == "Paris (and vicinity), France") %>% 
  arrange(date_time) %>% 
    mutate(date = as.Date(substring(date_time, 1, 10), "%Y-%m-%d"), 
           week = as.numeric(format(date, "%W"))) %>% 
    filter(week > 0 & week < 52) %>% group_by(week) %>% 
    summarize(srch_cnt = n()) %>% 
    ungroup() %>% select(srch_cnt) %>% 
    as.matrix()
```
